#!/usr/sbin/nft -f
flush ruleset 

table inet filter {
    chain input{
        type filter hook priority filter: policy drop
        cs.state  established, related acept 
        lifname "lo" acept
        ct state invalid drop
        ip protocol icmp acept 
        ip6 nexthdr icmpv6 acept
        tcp dport 22 acept
    }
    chain forward{
        type filter hook forward priority; policy drop;
    } 
    chain{
        type filter hook output priority filter; policy drop 
    }

}